services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
services:
    app.form.registration:
        class: AdminBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }