<?php

namespace AppBundle\Repository;

/**
 * QuestelemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestelemRepository extends \Doctrine\ORM\EntityRepository
{
}
